# Generated by Django 5.2.17 on 2026-09-05 08:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('interval', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=16)),
                ('proration_method', models.CharField(default='UNDECIDED', help_text='ADR-008 is still open. Stored, not yet acted on — T-20 owns this.', max_length=40)),
                ('cancellation_policy', models.CharField(default='UNDECIDED', help_text='ADR-008 is still open. Stored, not yet acted on — T-30 owns this.', max_length=40)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalChainRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_min', models.DecimalField(decimal_places=2, max_digits=8)),
                ('score_max', models.DecimalField(decimal_places=2, max_digits=8)),
                ('requires_manager', models.BooleanField(default=False)),
                ('requires_finance', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['score_min'],
                'constraints': [models.CheckConstraint(condition=models.Q(('score_max__gte', models.F('score_min'))), name='chain_rule_band_ordered'), models.CheckConstraint(condition=models.Q(('score_min__gte', 0)), name='chain_rule_min_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='CustomerTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('max_discount_pct', models.DecimalField(decimal_places=2, help_text='Tier-level discount ceiling, in percentage points.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'ordering': ['max_discount_pct', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_discount_pct__gte', 0), ('max_discount_pct__lte', 100)), name='customer_tier_max_discount_in_range')],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='core.customertier')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='unit', max_length=24)),
                ('tax_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('description', models.TextField(blank=True, default='')),
                ('is_promoted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.category')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.subscriptionplan')),
            ],
            options={
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=60)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.product')),
            ],
            options={
                'ordering': ['product__name', 'attribute', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('stage', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('SENT', 'Sent'), ('UNDER_NEGOTIATION', 'Under negotiation'), ('CONFIRMED', 'Confirmed'), ('FULFILLED', 'Fulfilled'), ('INVOICED', 'Invoiced'), ('PAID', 'Paid')], default='DRAFT', max_length=24)),
                ('order_discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margin_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margin_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('portal_token', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='core.customer')),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially paid'), ('PAID', 'Paid')], default='DRAFT', max_length=16)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('is_credit_note', models.BooleanField(default=False)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.quotation')),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('reason', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='core.quotation')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('level', models.CharField(choices=[('MANAGER', 'Sales Manager'), ('FINANCE', 'Finance')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned for revision')], default='PENDING', max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='core.quotation')),
            ],
            options={
                'ordering': ['quotation_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_type', models.CharField(choices=[('ONE_TIME', 'One-time'), ('RECURRING', 'Recurring')], default='ONE_TIME', max_length=16)),
                ('added_via_upsell', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_lines', to='core.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.quotation')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_lines', to='core.productvariant')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_lines', to='core.subscriptionplan')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PortalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(choices=[('CUSTOMER', 'Customer'), ('REP', 'Sales Rep')], max_length=16)),
                ('body', models.TextField(blank=True, default='')),
                ('counter_discount_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_messages', to='core.quotation')),
                ('quotation_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_messages', to='core.quotationline')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BillingScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('BILLED', 'Billed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=16)),
                ('is_proration_adjustment', models.BooleanField(default=False)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_schedule', to='core.quotation')),
                ('quotation_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_schedule', to='core.quotationline')),
            ],
            options={
                'verbose_name_plural': 'billing schedule entries',
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('shipping_cost_weight', models.DecimalField(decimal_places=2, default=1, help_text='Relative cost of shipping one unit from here. Lower ships first (ADR-006).', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['shipping_cost_weight', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('shipping_cost_weight__gte', 0)), name='warehouse_shipping_weight_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_on_hand', models.PositiveIntegerField(default=0)),
                ('qty_reserved', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_rows', to='core.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_rows', to='core.warehouse')),
            ],
            options={
                'verbose_name_plural': 'stock',
                'ordering': ['warehouse__name', 'product__name'],
            },
        ),
        migrations.CreateModel(
            name='FulfilmentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('is_backorder', models.BooleanField(default=False)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.quotation')),
                ('quotation_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.quotationline')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='core.warehouse')),
            ],
            options={
                'ordering': ['quotation_line_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryDiscountCeiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_discount_pct', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_ceilings', to='core.category')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_ceilings', to='core.customertier')),
            ],
            options={
                'ordering': ['tier__name', 'category__name'],
                'constraints': [models.UniqueConstraint(fields=('tier', 'category'), name='unique_ceiling_per_tier_category'), models.CheckConstraint(condition=models.Q(('max_discount_pct__gte', 0), ('max_discount_pct__lte', 100)), name='category_ceiling_in_range')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(default='BANK_TRANSFER', max_length=40)),
                ('paid_at', models.DateTimeField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.invoice')),
            ],
            options={
                'ordering': ['paid_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='PriceListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_entries', to='core.customertier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_entries', to='core.product')),
            ],
            options={
                'verbose_name_plural': 'price list entries',
                'ordering': ['product__name', 'tier__name'],
                'constraints': [models.UniqueConstraint(fields=('product', 'tier', 'currency'), name='unique_price_per_product_tier_currency'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_list_price_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='ProductPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_purchase_count', models.PositiveIntegerField(default=0)),
                ('product_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_a', to='core.product')),
                ('product_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_b', to='core.product')),
            ],
            options={
                'ordering': ['-co_purchase_count'],
                'constraints': [models.UniqueConstraint(fields=('product_a', 'product_b'), name='unique_product_pair'), models.CheckConstraint(condition=models.Q(('product_a', models.F('product_b')), _negated=True), name='product_pair_not_self')],
            },
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'attribute', 'value'), name='unique_variant_per_product'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(condition=models.Q(('order_discount_pct__gte', 0), ('order_discount_pct__lte', 100)), name='quotation_order_discount_in_range'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(condition=models.Q(('risk_score__gte', 0)), name='quotation_risk_score_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='invoice_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.UniqueConstraint(fields=('quotation', 'sequence'), name='unique_step_sequence_per_quotation'),
        ),
        migrations.AddConstraint(
            model_name='portalmessage',
            constraint=models.CheckConstraint(condition=models.Q(('counter_discount_pct__isnull', True), models.Q(('counter_discount_pct__gte', 0), ('counter_discount_pct__lte', 100)), _connector='OR'), name='portal_counter_discount_in_range'),
        ),
        migrations.AddConstraint(
            model_name='quotationline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_pct__gte', 0), ('discount_pct__lte', 100)), name='quotation_line_discount_in_range'),
        ),
        migrations.AddConstraint(
            model_name='quotationline',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='quotation_line_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='quotationline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('line_type', 'RECURRING'), ('subscription_plan__isnull', False)), models.Q(('line_type', 'ONE_TIME'), ('subscription_plan__isnull', True)), _connector='OR'), name='recurring_line_has_plan_one_time_does_not'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('list_price__gte', 0)), name='product_list_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='product_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('tax_pct__gte', 0), ('tax_pct__lte', 100)), name='product_tax_pct_in_range'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse'), name='unique_stock_per_product_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('qty_reserved__lte', models.F('qty_on_hand'))), name='stock_reserved_not_over_on_hand'),
        ),
        migrations.AddConstraint(
            model_name='fulfilmentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='fulfilment_allocation_qty_positive'),
        ),
    ]
