# Generated by Django 5.2.17 on 2026-09-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_subscriptionplan_approvalchainrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_days', models.PositiveIntegerField(default=7, help_text='A quotation with no activity for this many days is stalled (PDF B9).')),
                ('anomaly_window_days', models.PositiveIntegerField(default=90, help_text="How far back a rep's historical average discount is computed.")),
                ('anomaly_threshold_pct', models.DecimalField(decimal_places=2, default=10, help_text="Percentage points above the rep's own average that counts as an anomaly.", max_digits=5)),
                ('delivery_promise_days', models.PositiveIntegerField(default=5, help_text='Days after confirmation that an order is promised for (ADR-007).')),
            ],
            options={
                'verbose_name': 'sales setting',
                'verbose_name_plural': 'sales settings',
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='promised_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='reorder_point',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
