# Generated by Django 5.2.17 on 2026-09-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_salessetting_quotation_promised_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessetting',
            name='currency_code',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='salessetting',
            name='currency_rate',
            field=models.DecimalField(decimal_places=6, default=1, help_text='Display units per 1.00 stored. 1.000000 means prices are already in this currency.', max_digits=12),
        ),
        migrations.AddField(
            model_name='salessetting',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=4),
        ),
        migrations.AlterField(
            model_name='pricelistentry',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
