# Generated by Django 5.2.17 on 2026-09-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_salessetting_currency_code_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='billingscheduleentry',
            index=models.Index(fields=['status', 'due_date'], name='schedule_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['stage', '-last_activity_at'], name='quote_stage_activity_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['last_activity_at'], name='quote_activity_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['rep', '-created_at'], name='quote_rep_created_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['promised_delivery_date'], name='quote_promised_idx'),
        ),
    ]
