# Generated by Django 5.2.17 on 2026-09-05 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_billingscheduleentry_schedule_status_due_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RENEWED', 'Renewed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('mrr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cancelled_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='core.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='core.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='core.quotation')),
                ('renewed_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_assets', to='core.quotation')),
                ('source_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='core.quotationline')),
            ],
            options={
                'ordering': ['customer__name', 'product__name', '-start_date'],
                'indexes': [models.Index(fields=['customer', 'status'], name='asset_customer_status_idx'), models.Index(fields=['status', 'end_date'], name='asset_status_end_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('qty__gte', 1)), name='asset_qty_at_least_one'), models.CheckConstraint(condition=models.Q(('mrr__gte', 0)), name='asset_mrr_non_negative'), models.UniqueConstraint(fields=('source_line',), name='unique_asset_per_line')],
            },
        ),
    ]
