# Generated by Django 5.2.17 on 2026-09-05 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='amends_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='core.asset'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='kind',
            field=models.CharField(choices=[('NEW', 'New business'), ('RENEWAL', 'Renewal'), ('AMENDMENT', 'Amendment')], default='NEW', max_length=16),
        ),
    ]
