"""Specification tests for the blended discount risk score (BR-1 / ADR-005).

**These two tests ARE the specification.** They are the two worked examples from
PDF §10, restated in SPEC.md BR-1 and in DECISIONS.md ADR-005, written *before*
`core/services/risk.py` exists. T-09's job is to make them pass.

If T-09 produces a different number, the implementation is wrong — not the test.
Do not edit this file to match whatever the implementation happens to compute.
Changing these expectations means changing the product's core business rule, and
that requires amending ADR-005 first, in writing, with a reason.

The service layer is plain Python (ARCHITECTURE.md), so these tests construct
plain dicts and Decimals. No database, no fixtures, no ORM objects.

The API under test, as fixed by ADR-005:

    score_quotation(
        lines,                      # iterable of dicts, see below
        tier_max_discount_pct,      # Decimal — CustomerTier.max_discount_pct
        category_ceilings,          # dict: category name -> Decimal max pct,
                                    #   already resolved for this customer's tier
        order_discount_pct=Decimal("0"),   # Quotation.order_discount_pct
    ) -> RiskResult

    line dict keys: line_id, label, category, discount_pct

    RiskResult.score      Decimal, quantised to 0.01 — total points over ceiling
    RiskResult.flagged    bool — True when score > 0, i.e. approval is required
    RiskResult.breakdown  list[RiskLine], one per input line, same order

    RiskLine.line_id / .label / .category
    RiskLine.given_pct    Decimal — line discount combined with the order discount
    RiskLine.allowed_pct  Decimal — min(tier ceiling, category ceiling)
    RiskLine.over_by_pct  Decimal — max(0, given - allowed)
"""

import unittest
from decimal import Decimal

from django.test import TestCase

from core.models import (
    Category,
    CategoryDiscountCeiling,
    Customer,
    CustomerTier,
    Product,
    Quotation,
    QuotationLine,
    Role,
    User,
)
from core.services.risk import effective_ceiling, score_for_quotation

def _risk_is_implemented():
    """True once `score_quotation` actually computes something.

    The contract pass (before T-09) creates `core/services/risk.py` with the real
    signatures and `NotImplementedError` bodies, so "the module imports" stopped being
    a useful signal. This probes for a *working* implementation instead: a stub raises
    NotImplementedError and is skipped; anything else runs and is judged by the real
    assertions below.

    **This changes the skip condition only.** No expectation in this file has been
    relaxed — the two tests still assert exactly the numbers ADR-005 fixed.
    """
    try:
        from core.services.risk import score_quotation
    except ImportError:  # pragma: no cover - before the contract pass
        return False
    try:
        score_quotation(
            lines=[],
            tier_max_discount_pct=Decimal("0"),
            category_ceilings={},
        )
    except NotImplementedError:  # pragma: no cover - contract stub, not yet built
        return False
    except Exception:  # noqa: BLE001 - it does something; let the assertions judge it
        return True
    return True


RISK_IMPLEMENTED = _risk_is_implemented()

if RISK_IMPLEMENTED:
    from core.services.risk import score_quotation


GOLD_TIER_CEILING = Decimal("15")

# CategoryDiscountCeiling rows for the Gold tier, per DEMO.md's seed data.
GOLD_CATEGORY_CEILINGS = {
    "Hardware": Decimal("15"),
    "Services": Decimal("10"),
    "Subscriptions": Decimal("12"),
}


@unittest.skipUnless(
    RISK_IMPLEMENTED,
    "core.services.risk is still a contract stub — T-09 implements it",
)
class BlendedRiskScoreSpecTests(unittest.TestCase):
    """PDF §10's two worked examples, asserted directly."""

    def test_pdf_example_1_single_line_eight_points_over_flags_the_quotation(self):
        """Gold customer. Hardware 12% is fine; Services 18% is 8 points over.

        The PDF's point: 15% "sounds fine on paper" for a Gold customer, but the
        Services ceiling is 10%, so the setup service line is 8 points over its
        *own* ceiling and the whole quotation is flagged — because of that one
        line, even though the hardware line is comfortably inside its limit.
        """
        result = score_quotation(
            lines=[
                {
                    "line_id": 1,
                    "label": "Laptop Pro 14",
                    "category": "Hardware",
                    "discount_pct": Decimal("12"),
                },
                {
                    "line_id": 2,
                    "label": "Onsite Setup Service",
                    "category": "Services",
                    "discount_pct": Decimal("18"),
                },
            ],
            tier_max_discount_pct=GOLD_TIER_CEILING,
            category_ceilings=GOLD_CATEGORY_CEILINGS,
        )

        # The whole quotation is flagged for approval.
        self.assertTrue(
            result.flagged,
            "an 18% Services line against a 10% ceiling must flag the quotation",
        )
        self.assertEqual(Decimal("8.00"), result.score)

        # The approval screen cannot explain itself without the breakdown.
        laptop, service = result.breakdown

        self.assertEqual(Decimal("12"), laptop.given_pct)
        self.assertEqual(Decimal("15"), laptop.allowed_pct)
        self.assertEqual(
            Decimal("0"),
            laptop.over_by_pct,
            "Hardware at 12% is inside the 15% Hardware ceiling",
        )

        self.assertEqual(Decimal("18"), service.given_pct)
        self.assertEqual(
            Decimal("10"),
            service.allowed_pct,
            "effective ceiling is the stricter of tier (15) and category (10)",
        )
        self.assertEqual(Decimal("8"), service.over_by_pct)

    def test_pdf_example_2_several_small_overages_accumulate_into_a_flag(self):
        """No line looks alarming alone; together they give away real margin.

        Three lines, each only 2, 3 and 2 points over their own ceilings. The
        blended score adds them up so "small violations spread across many lines
        cannot slip through unnoticed" — total 7 points over, quotation flagged.
        """
        result = score_quotation(
            lines=[
                {
                    "line_id": 1,
                    "label": "Laptop Pro 14",
                    "category": "Hardware",
                    "discount_pct": Decimal("17"),  # ceiling 15 -> 2 over
                },
                {
                    "line_id": 2,
                    "label": "Onsite Setup Service",
                    "category": "Services",
                    "discount_pct": Decimal("13"),  # ceiling 10 -> 3 over
                },
                {
                    "line_id": 3,
                    "label": "Care Plan 2yr",
                    "category": "Subscriptions",
                    "discount_pct": Decimal("14"),  # ceiling 12 -> 2 over
                },
            ],
            tier_max_discount_pct=GOLD_TIER_CEILING,
            category_ceilings=GOLD_CATEGORY_CEILINGS,
        )

        self.assertEqual(
            [Decimal("2"), Decimal("3"), Decimal("2")],
            [line.over_by_pct for line in result.breakdown],
            "each line is measured against its own effective ceiling",
        )

        self.assertTrue(
            result.flagged,
            "several small overages must accumulate into a flag (PDF §10)",
        )
        self.assertEqual(
            Decimal("7.00"),
            result.score,
            "2 + 3 + 2 points over = a blended score of 7",
        )

        # Routing consequence, per the ApprovalChainRule rows prescribed by
        # ADR-005: 7 points lands in the Manager-only band (0.01 - 7.99), while
        # example 1's 8 points crosses into Manager + Finance (8.00 and above).
        # The band boundaries themselves live in the database, not here.
        self.assertLess(result.score, Decimal("8"))


if __name__ == "__main__":  # pragma: no cover
    unittest.main()


# ---------------------------------------------------------------------------
# Added by T-09, alongside the two specification tests above. These cover paths
# the PDF's examples do not reach. They must never be used to justify weakening
# an assertion in BlendedRiskScoreSpecTests.
# ---------------------------------------------------------------------------


class RiskEdgeCaseTests(unittest.TestCase):
    """Paths the two worked examples do not exercise."""

    def test_empty_quotation_scores_zero_and_does_not_flag(self):
        """The seeded Acme draft is empty, so this is a real path, not a corner."""
        result = score_quotation(
            lines=[],
            tier_max_discount_pct=GOLD_TIER_CEILING,
            category_ceilings=GOLD_CATEGORY_CEILINGS,
        )
        self.assertEqual(Decimal("0.00"), result.score)
        self.assertFalse(result.flagged)
        self.assertEqual([], result.breakdown)

    def test_category_with_no_ceiling_row_falls_back_to_the_tier_ceiling(self):
        result = score_quotation(
            lines=[{
                "line_id": 1, "label": "Mystery", "category": "Uncategorised",
                "discount_pct": Decimal("18"),
            }],
            tier_max_discount_pct=GOLD_TIER_CEILING,
            category_ceilings=GOLD_CATEGORY_CEILINGS,
        )
        line = result.breakdown[0]
        self.assertEqual(Decimal("15"), line.allowed_pct)
        self.assertEqual(Decimal("3"), line.over_by_pct)

    def test_a_looser_category_ceiling_cannot_lift_a_line_past_the_tier_cap(self):
        """min(tier, category) - the stricter always wins (invariant 14)."""
        result = score_quotation(
            lines=[{
                "line_id": 1, "label": "Setup", "category": "Services",
                "discount_pct": Decimal("18"),
            }],
            tier_max_discount_pct=Decimal("15"),
            category_ceilings={"Services": Decimal("20")},
        )
        self.assertEqual(Decimal("15"), result.breakdown[0].allowed_pct)
        self.assertEqual(Decimal("3.00"), result.score)

    def test_order_discount_compounds_with_the_line_discount(self):
        """Two discounts do not add: 10% then 5% is 14.5%, not 15%."""
        result = score_quotation(
            lines=[{
                "line_id": 1, "label": "Laptop", "category": "Hardware",
                "discount_pct": Decimal("10"),
            }],
            tier_max_discount_pct=GOLD_TIER_CEILING,
            category_ceilings=GOLD_CATEGORY_CEILINGS,
            order_discount_pct=Decimal("5"),
        )
        self.assertEqual(Decimal("14.5"), result.breakdown[0].given_pct)
        self.assertEqual(Decimal("0.00"), result.score)

    def test_an_order_discount_alone_can_push_a_line_over(self):
        result = score_quotation(
            lines=[{
                "line_id": 1, "label": "Setup", "category": "Services",
                "discount_pct": Decimal("8"),
            }],
            tier_max_discount_pct=GOLD_TIER_CEILING,
            category_ceilings=GOLD_CATEGORY_CEILINGS,
            order_discount_pct=Decimal("10"),
        )
        # 8% then 10% = 17.2%, against the 10% Services ceiling -> 7.2 over.
        self.assertEqual(Decimal("17.2"), result.breakdown[0].given_pct)
        self.assertEqual(Decimal("7.20"), result.score)
        self.assertTrue(result.flagged)

    def test_breakdown_keeps_input_order_and_reports_every_line(self):
        result = score_quotation(
            lines=[
                {"line_id": 7, "label": "A", "category": "Hardware", "discount_pct": Decimal("1")},
                {"line_id": 8, "label": "B", "category": "Services", "discount_pct": Decimal("2")},
                {"line_id": 9, "label": "C", "category": "Subscriptions", "discount_pct": Decimal("3")},
            ],
            tier_max_discount_pct=GOLD_TIER_CEILING,
            category_ceilings=GOLD_CATEGORY_CEILINGS,
        )
        self.assertEqual([7, 8, 9], [line.line_id for line in result.breakdown])
        self.assertEqual([], result.offending_lines)

    def test_effective_ceiling_helper_matches_what_the_score_uses(self):
        self.assertEqual(Decimal("10"), effective_ceiling(Decimal("15"), Decimal("10")))
        self.assertEqual(Decimal("15"), effective_ceiling(Decimal("15"), Decimal("20")))
        self.assertEqual(Decimal("15"), effective_ceiling(Decimal("15"), None))


class ScoreForQuotationTests(TestCase):
    """The ORM adapter, against real configuration rows."""

    def setUp(self):
        gold = CustomerTier.objects.create(name="Gold", max_discount_pct=Decimal("15"))
        hardware = Category.objects.create(name="Hardware")
        services = Category.objects.create(name="Services")
        CategoryDiscountCeiling.objects.create(
            tier=gold, category=hardware, max_discount_pct=Decimal("15")
        )
        CategoryDiscountCeiling.objects.create(
            tier=gold, category=services, max_discount_pct=Decimal("10")
        )
        customer = Customer.objects.create(name="Acme", email="a@a.test", tier=gold)
        rep = User.objects.create_user(
            email="rep@risk.test", password="x", name="Rep", role=Role.REP
        )
        self.quotation = Quotation.objects.create(
            number="Q-RISK-1", customer=customer, rep=rep,
            last_activity_at="2026-09-05T10:00:00Z",
        )
        laptop = Product.objects.create(
            name="Laptop Pro 14", category=hardware,
            list_price=Decimal("1450"), cost=Decimal("1050"),
        )
        setup = Product.objects.create(
            name="Onsite Setup Service", category=services,
            list_price=Decimal("600"), cost=Decimal("330"),
        )
        QuotationLine.objects.create(
            quotation=self.quotation, product=laptop, qty=6,
            unit_price=Decimal("1450"), discount_pct=Decimal("12"),
        )
        QuotationLine.objects.create(
            quotation=self.quotation, product=setup, qty=1,
            unit_price=Decimal("600"), discount_pct=Decimal("18"),
        )

    def test_reproduces_the_pdf_example_from_database_rows(self):
        result = score_for_quotation(self.quotation)
        self.assertEqual(Decimal("8.00"), result.score)
        self.assertTrue(result.flagged)
        self.assertEqual(1, len(result.offending_lines))
        self.assertEqual("Onsite Setup Service", result.offending_lines[0].label)

    def test_reads_only_and_does_not_write_the_snapshot(self):
        """approval.py stores risk_score at submit time - not this function."""
        score_for_quotation(self.quotation)
        self.quotation.refresh_from_db()
        self.assertEqual(Decimal("0.00"), self.quotation.risk_score)

    def test_loosening_the_ceiling_row_changes_the_score_with_no_code_change(self):
        """Configuration drives the score. No constant in code decides this.

        Note what loosening the CATEGORY ceiling alone can and cannot do. Raising
        Services from 10 to 18 moves the score from 8.00 to 3.00 - not to zero -
        because the effective ceiling is min(tier 15, category 18) = 15, and the
        line is discounted 18%. The stricter of the two always wins (invariant 14).
        """
        CategoryDiscountCeiling.objects.filter(category__name="Services").update(
            max_discount_pct=Decimal("18")
        )
        self.assertEqual(Decimal("3.00"), score_for_quotation(self.quotation).score)

    def test_only_raising_the_tier_ceiling_too_takes_the_score_to_zero(self):
        CategoryDiscountCeiling.objects.filter(category__name="Services").update(
            max_discount_pct=Decimal("18")
        )
        CustomerTier.objects.filter(name="Gold").update(max_discount_pct=Decimal("18"))
        self.quotation.refresh_from_db()
        result = score_for_quotation(self.quotation)
        self.assertEqual(Decimal("0.00"), result.score)
        self.assertFalse(result.flagged)
