"""Specification tests for the blended discount risk score (BR-1 / ADR-005).

**These two tests ARE the specification.** They are the two worked examples from
PDF §10, restated in SPEC.md BR-1 and in DECISIONS.md ADR-005, written *before*
`core/services/risk.py` exists. T-09's job is to make them pass.

If T-09 produces a different number, the implementation is wrong — not the test.
Do not edit this file to match whatever the implementation happens to compute.
Changing these expectations means changing the product's core business rule, and
that requires amending ADR-005 first, in writing, with a reason.

The service layer is plain Python (ARCHITECTURE.md), so these tests construct
plain dicts and Decimals. No database, no fixtures, no ORM objects.

The API under test, as fixed by ADR-005:

    score_quotation(
        lines,                      # iterable of dicts, see below
        tier_max_discount_pct,      # Decimal — CustomerTier.max_discount_pct
        category_ceilings,          # dict: category name -> Decimal max pct,
                                    #   already resolved for this customer's tier
        order_discount_pct=Decimal("0"),   # Quotation.order_discount_pct
    ) -> RiskResult

    line dict keys: line_id, label, category, discount_pct

    RiskResult.score      Decimal, quantised to 0.01 — total points over ceiling
    RiskResult.flagged    bool — True when score > 0, i.e. approval is required
    RiskResult.breakdown  list[RiskLine], one per input line, same order

    RiskLine.line_id / .label / .category
    RiskLine.given_pct    Decimal — line discount combined with the order discount
    RiskLine.allowed_pct  Decimal — min(tier ceiling, category ceiling)
    RiskLine.over_by_pct  Decimal — max(0, given - allowed)
"""

import unittest
from decimal import Decimal

def _risk_is_implemented():
    """True once `score_quotation` actually computes something.

    The contract pass (before T-09) creates `core/services/risk.py` with the real
    signatures and `NotImplementedError` bodies, so "the module imports" stopped being
    a useful signal. This probes for a *working* implementation instead: a stub raises
    NotImplementedError and is skipped; anything else runs and is judged by the real
    assertions below.

    **This changes the skip condition only.** No expectation in this file has been
    relaxed — the two tests still assert exactly the numbers ADR-005 fixed.
    """
    try:
        from core.services.risk import score_quotation
    except ImportError:  # pragma: no cover - before the contract pass
        return False
    try:
        score_quotation(
            lines=[],
            tier_max_discount_pct=Decimal("0"),
            category_ceilings={},
        )
    except NotImplementedError:  # pragma: no cover - contract stub, not yet built
        return False
    except Exception:  # noqa: BLE001 - it does something; let the assertions judge it
        return True
    return True


RISK_IMPLEMENTED = _risk_is_implemented()

if RISK_IMPLEMENTED:
    from core.services.risk import score_quotation


GOLD_TIER_CEILING = Decimal("15")

# CategoryDiscountCeiling rows for the Gold tier, per DEMO.md's seed data.
GOLD_CATEGORY_CEILINGS = {
    "Hardware": Decimal("15"),
    "Services": Decimal("10"),
    "Subscriptions": Decimal("12"),
}


@unittest.skipUnless(
    RISK_IMPLEMENTED,
    "core.services.risk is still a contract stub — T-09 implements it",
)
class BlendedRiskScoreSpecTests(unittest.TestCase):
    """PDF §10's two worked examples, asserted directly."""

    def test_pdf_example_1_single_line_eight_points_over_flags_the_quotation(self):
        """Gold customer. Hardware 12% is fine; Services 18% is 8 points over.

        The PDF's point: 15% "sounds fine on paper" for a Gold customer, but the
        Services ceiling is 10%, so the setup service line is 8 points over its
        *own* ceiling and the whole quotation is flagged — because of that one
        line, even though the hardware line is comfortably inside its limit.
        """
        result = score_quotation(
            lines=[
                {
                    "line_id": 1,
                    "label": "Laptop Pro 14",
                    "category": "Hardware",
                    "discount_pct": Decimal("12"),
                },
                {
                    "line_id": 2,
                    "label": "Onsite Setup Service",
                    "category": "Services",
                    "discount_pct": Decimal("18"),
                },
            ],
            tier_max_discount_pct=GOLD_TIER_CEILING,
            category_ceilings=GOLD_CATEGORY_CEILINGS,
        )

        # The whole quotation is flagged for approval.
        self.assertTrue(
            result.flagged,
            "an 18% Services line against a 10% ceiling must flag the quotation",
        )
        self.assertEqual(Decimal("8.00"), result.score)

        # The approval screen cannot explain itself without the breakdown.
        laptop, service = result.breakdown

        self.assertEqual(Decimal("12"), laptop.given_pct)
        self.assertEqual(Decimal("15"), laptop.allowed_pct)
        self.assertEqual(
            Decimal("0"),
            laptop.over_by_pct,
            "Hardware at 12% is inside the 15% Hardware ceiling",
        )

        self.assertEqual(Decimal("18"), service.given_pct)
        self.assertEqual(
            Decimal("10"),
            service.allowed_pct,
            "effective ceiling is the stricter of tier (15) and category (10)",
        )
        self.assertEqual(Decimal("8"), service.over_by_pct)

    def test_pdf_example_2_several_small_overages_accumulate_into_a_flag(self):
        """No line looks alarming alone; together they give away real margin.

        Three lines, each only 2, 3 and 2 points over their own ceilings. The
        blended score adds them up so "small violations spread across many lines
        cannot slip through unnoticed" — total 7 points over, quotation flagged.
        """
        result = score_quotation(
            lines=[
                {
                    "line_id": 1,
                    "label": "Laptop Pro 14",
                    "category": "Hardware",
                    "discount_pct": Decimal("17"),  # ceiling 15 -> 2 over
                },
                {
                    "line_id": 2,
                    "label": "Onsite Setup Service",
                    "category": "Services",
                    "discount_pct": Decimal("13"),  # ceiling 10 -> 3 over
                },
                {
                    "line_id": 3,
                    "label": "Care Plan 2yr",
                    "category": "Subscriptions",
                    "discount_pct": Decimal("14"),  # ceiling 12 -> 2 over
                },
            ],
            tier_max_discount_pct=GOLD_TIER_CEILING,
            category_ceilings=GOLD_CATEGORY_CEILINGS,
        )

        self.assertEqual(
            [Decimal("2"), Decimal("3"), Decimal("2")],
            [line.over_by_pct for line in result.breakdown],
            "each line is measured against its own effective ceiling",
        )

        self.assertTrue(
            result.flagged,
            "several small overages must accumulate into a flag (PDF §10)",
        )
        self.assertEqual(
            Decimal("7.00"),
            result.score,
            "2 + 3 + 2 points over = a blended score of 7",
        )

        # Routing consequence, per the ApprovalChainRule rows prescribed by
        # ADR-005: 7 points lands in the Manager-only band (0.01 - 7.99), while
        # example 1's 8 points crosses into Manager + Finance (8.00 and above).
        # The band boundaries themselves live in the database, not here.
        self.assertLess(result.score, Decimal("8"))


if __name__ == "__main__":  # pragma: no cover
    unittest.main()
